name: Package Scripts
on: push
jobs:
  scripts-ubuntu:
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Deploy
        run: printf 'y\n' | yarn deploy
      - name: Start
        run: bash .github/scripts/runfe.sh
  scripts-mac:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Deploy
        run: printf 'y\n' | yarn deploy
      - name: Install timeout
        run: brew install coreutils
      - name: Start
        run: bash .github/scripts/runfe.sh
